// svelte-app/src/lib/components/Footer.svelte
<script>
  import { footerServicesIndexOrder, footerServicesDefaultOrder, contact } from '$lib/site-data.js';
  import ActiveContact from '$lib/components/ActiveContact.svelte';

  /** @type {'index' | 'default'} - index = home page order, default = contact/free-quote order */
  export let serviceLinksOrder = 'index';

  const year = new Date().getFullYear();
  const footerLinks =
    serviceLinksOrder === 'index' ? footerServicesIndexOrder : footerServicesDefaultOrder;

  const linkClass =
    'transition-colors duration-200 hover:text-[#d32f2f] focus-visible:text-[#d32f2f] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white/50 rounded';
  const headingClass = 'font-bold text-sm uppercase tracking-wide mb-4 text-center text-white/90';
</script>

<footer class="bg-gradient-to-r from-[#3a3a3a] to-[#1a1a1a] text-white pt-16 pb-12">
  <div class="container mx-auto px-4 grid grid-cols-1 gap-10 md:grid-cols-4 md:gap-8">
    <!-- Brand -->
    <div class="flex flex-col items-center text-center md:items-center">
      <picture>
        <source srcset="/images/logo-on-dark.webp" type="image/webp" />
        <img
          src="/images/logo-on-dark.png"
          alt="OhMyGlass"
          class="h-24 w-auto mb-4"
          width="1000"
          height="491"
        />
      </picture>
      <p class="text-sm text-white/80">&copy; <span id="year">{year}</span> OhMyGlass. All rights reserved.</p>
    </div>

    <!-- Services -->
    <nav class="text-center" aria-label="Footer services">
      <h3 class={headingClass}>Our Services</h3>
      <ul class="space-y-2">
        {#each footerLinks as link}
          <li>
            <a href={link.href} class={linkClass}>{link.label}</a>
          </li>
        {/each}
      </ul>
    </nav>

    <!-- Contact -->
    <div class="text-center">
      <h3 class={headingClass}>Contact Us</h3>
      <ul class="space-y-2">
        <li>
          <ActiveContact let:phone let:phoneHref let:afterHoursPhone let:afterHoursPhoneHref>
            <a href={phoneHref} class={linkClass}>{phone}</a>
            <span class="block text-white/60 text-xs mt-1">After hours</span>
            <a href={afterHoursPhoneHref} class="{linkClass} text-sm">{afterHoursPhone}</a>
          </ActiveContact>
        </li>
        <li>
          <a href={contact.emailHref} class={linkClass}>{contact.email}</a>
          {#if contact.secondaryEmail}
            <span class="block text-white/60 text-xs mt-1">Secondary</span>
            <a href={contact.secondaryEmailHref} class="{linkClass} text-sm">{contact.secondaryEmail}</a>
          {/if}
        </li>
        <li>
          <a href={contact.googleMaps} target="_blank" rel="noopener noreferrer" class={linkClass}>Find Us on Map</a>
        </li>
        <li><a href={contact.serviceAreasHref} class={linkClass}>Service Areas</a></li>
      </ul>
    </div>

    <!-- Social -->
    <div class="text-center">
      <h3 class={headingClass}>Connect With Us</h3>
      <ul class="flex gap-4 justify-center" role="list">
        <li>
          <a href={contact.googleMaps} target="_blank" rel="noopener noreferrer" class="{linkClass} inline-flex items-center justify-center w-10 h-10" aria-label="Google Maps">
            <i class="fab fa-google" aria-hidden="true"></i>
          </a>
        </li>
        <li>
          <a href={contact.facebook} target="_blank" rel="noopener noreferrer" class="{linkClass} inline-flex items-center justify-center w-10 h-10" aria-label="Facebook">
            <i class="fab fa-facebook-f" aria-hidden="true"></i>
          </a>
        </li>
        <li>
          <a href={contact.instagram} target="_blank" rel="noopener noreferrer" class="{linkClass} inline-flex items-center justify-center w-10 h-10" aria-label="Instagram">
            <i class="fab fa-instagram" aria-hidden="true"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
</footer>

// next-app/src/components/footer.tsx
"use client";

import Link from "next/link";
import {
  footerServicesIndexOrder,
  footerServicesDefaultOrder,
  contact,
} from "@/lib/site-data";
import { ActiveContact } from "./active-contact";

const linkClass =
  "transition-colors duration-200 hover:text-[#d32f2f] focus-visible:text-[#d32f2f] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white/50 rounded";
const headingClass =
  "font-bold text-sm uppercase tracking-wide mb-4 text-center text-white/90";

export function Footer({ serviceLinksOrder = "index" }: { serviceLinksOrder?: "index" | "default" }) {
  const year = new Date().getFullYear();
  const footerLinks =
    serviceLinksOrder === "index" ? footerServicesIndexOrder : footerServicesDefaultOrder;

  return (
    <footer className="bg-gradient-to-r from-[#3a3a3a] to-[#1a1a1a] text-white pt-16 pb-12">
      <div className="container mx-auto px-4 grid grid-cols-1 gap-10 md:grid-cols-4 md:gap-8">
        <div className="flex flex-col items-center text-center md:items-center">
          <picture>
            <source srcSet="/images/logo-on-dark.webp" type="image/webp" />
            <img
              src="/images/logo-on-dark.png"
              alt="OhMyGlass"
              className="h-24 w-auto mb-4"
              width={1000}
              height={491}
            />
          </picture>
          <p className="text-sm text-white/80">
            &copy; {year} OhMyGlass. All rights reserved.
          </p>
        </div>

        <nav className="text-center" aria-label="Footer services">
          <h3 className={headingClass}>Our Services</h3>
          <ul className="space-y-2">
            {footerLinks.map((link) => (
              <li key={link.href}>
                <Link href={link.href} className={linkClass}>
                  {link.label}
                </Link>
              </li>
            ))}
          </ul>
        </nav>

        <div className="text-center">
          <h3 className={headingClass}>Contact Us</h3>
          <ul className="space-y-2">
            <li>
              <ActiveContact>
                {({ phone, phoneHref, afterHoursPhone, afterHoursPhoneHref }) => (
                  <>
                    <Link href={phoneHref} className={linkClass}>
                      {phone}
                    </Link>
                    <span className="block text-white/60 text-xs mt-1">After hours</span>
                    <Link href={afterHoursPhoneHref} className={`${linkClass} text-sm`}>
                      {afterHoursPhone}
                    </Link>
                  </>
                )}
              </ActiveContact>
            </li>
            <li>
              <Link href={contact.emailHref} className={linkClass}>
                {contact.email}
              </Link>
              {contact.secondaryEmail ? (
                <>
                  <span className="block text-white/60 text-xs mt-1">Secondary</span>
                  <Link href={contact.secondaryEmailHref} className={`${linkClass} text-sm`}>
                    {contact.secondaryEmail}
                  </Link>
                </>
              ) : null}
            </li>
            <li>
              <Link
                href={contact.googleMaps}
                target="_blank"
                rel="noopener noreferrer"
                className={linkClass}
              >
                Find Us on Map
              </Link>
            </li>
            <li>
              <Link href={contact.serviceAreasHref} className={linkClass}>
                Service Areas
              </Link>
            </li>
          </ul>
        </div>

        <div className="text-center">
          <h3 className={headingClass}>Connect With Us</h3>
          <ul className="flex gap-4 justify-center" role="list">
            <li>
              <Link
                href={contact.googleMaps}
                target="_blank"
                rel="noopener noreferrer"
                className={`${linkClass} inline-flex items-center justify-center w-10 h-10`}
                aria-label="Google Maps"
              >
                <i className="fab fa-google" aria-hidden="true" />
              </Link>
            </li>
            <li>
              <Link
                href={contact.facebook}
                target="_blank"
                rel="noopener noreferrer"
                className={`${linkClass} inline-flex items-center justify-center w-10 h-10`}
                aria-label="Facebook"
              >
                <i className="fab fa-facebook-f" aria-hidden="true" />
              </Link>
            </li>
            <li>
              <Link
                href={contact.instagram}
                target="_blank"
                rel="noopener noreferrer"
                className={`${linkClass} inline-flex items-center justify-center w-10 h-10`}
                aria-label="Instagram"
              >
                <i className="fab fa-instagram" aria-hidden="true" />
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  );
}
