// svelte-app/src/routes/contact/+page.svelte
<svelte:head>
  <title>Contact Us - OhMyGlass</title>
  <meta name="description" content="Contact OhMyGlass for any inquiries about our glass repair and replacement services in the Greater Toronto Area (GTA). We're here to help." />
  <meta name="keywords" content="contact ohmyglass, glass repair contact, window replacement contact, GTA glass services" />
  <meta property="og:title" content="Contact OhMyGlass" />
  <meta property="og:description" content="Get in touch with OhMyGlass for professional glass services in the Greater Toronto Area. We look forward to hearing from you." />
  <meta property="og:image" content={ogImage} />
  <meta property="fb:app_id" content="966242223397117" />
  <meta property="og:site_name" content="OhMyGlass" />
  <meta property="og:url" content={siteUrl + '/contact'} />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="Contact Us" />
  <meta name="twitter:description" content="Get in touch with OhMyGlass for professional glass services in the Greater Toronto Area. We look forward to hearing from you." />
  <meta name="twitter:image" content={ogImage} />
  <meta property="og:type" content="website" />
  <meta property="og:locale" content="en_CA" />
  <link rel="canonical" href={siteUrl + '/contact'} />
  {@html getJsonLdScriptTag(contactPageSchema)}
  {@html getJsonLdScriptTag(contactBreadcrumbSchema)}
</svelte:head>

<script>
  import CtaFormSection from '$lib/components/CtaFormSection.svelte';
  import Footer from '$lib/components/Footer.svelte';
  import { getBreadcrumbSchema, getJsonLdScriptTag } from '$lib/schema.js';
  import { nap, contact, withInternalUtm, siteUrl, ogImage } from '$lib/site-data.js';

  const contactBreadcrumbSchema = getBreadcrumbSchema([
    { name: 'Home', url: '/' },
    { name: 'Contact', url: '/contact' }
  ]);
  const contactPageSchema = {
    '@context': 'https://schema.org',
    '@type': 'ContactPage',
    name: 'Contact Us - OhMyGlass',
    description: 'Contact OhMyGlass for professional glass repair and replacement services in the Greater Toronto Area.',
    url: siteUrl + '/contact',
    mainEntity: {
      '@type': 'LocalBusiness',
      name: nap.name,
      telephone: nap.telephoneSchema,
      email: [contact.email, contact.secondaryEmail],
      address: {
        '@type': 'PostalAddress',
        streetAddress: nap.address.streetAddress,
        addressLocality: nap.address.addressLocality,
        addressRegion: nap.address.addressRegion,
        addressCountry: nap.address.addressCountry
      },
      url: siteUrl
    }
  };
</script>

<CtaFormSection
  title="Contact Us"
  description="Have a question or need to get in touch? Fill out the form below and we'll get back to you quickly. You can also reach us by phone or email."
  showContactStrip={true}
  formTitle="OhMyGlass Contact Form"
/>

<section class="bg-[#f5f7fa] py-6 text-center">
  <p class="text-gray-600">
    Serving the Greater Toronto Area.
    <a href={withInternalUtm('/service-areas', 'contact')} class="text-[#d32f2f] font-semibold hover:underline">View Service Areas</a>
  </p>
</section>
<Footer serviceLinksOrder="default" />

// next-app/src/app/contact/page.tsx
import type { Metadata } from "next";
import { getBreadcrumbSchema, safeJsonLdScript } from "@/lib/schema";
import { nap, contact, siteUrl, ogImage } from "@/lib/site-data";
import { ContactPageView } from "@/components/contact-page-view";

const contactBreadcrumbSchema = getBreadcrumbSchema([
  { name: "Home", url: "/" },
  { name: "Contact", url: "/contact" },
]);

const contactPageSchema = {
  "@context": "https://schema.org",
  "@type": "ContactPage",
  name: "Contact Us - OhMyGlass",
  description:
    "Contact OhMyGlass for professional glass repair and replacement services in the Greater Toronto Area.",
  url: siteUrl + "/contact",
  mainEntity: {
    "@type": "LocalBusiness",
    name: nap.name,
    telephone: nap.telephoneSchema,
    email: [contact.email, contact.secondaryEmail],
    address: {
      "@type": "PostalAddress",
      streetAddress: nap.address.streetAddress,
      addressLocality: nap.address.addressLocality,
      addressRegion: nap.address.addressRegion,
      addressCountry: nap.address.addressCountry,
    },
    url: siteUrl,
  },
};

export const metadata: Metadata = {
  title: "Contact Us - OhMyGlass",
  description:
    "Contact OhMyGlass for any inquiries about our glass repair and replacement services in the Greater Toronto Area (GTA). We're here to help.",
  keywords: ["contact ohmyglass", "glass repair contact", "window replacement contact", "GTA glass services"],
  alternates: { canonical: siteUrl + "/contact" },
  openGraph: {
    title: "Contact OhMyGlass",
    description:
      "Get in touch with OhMyGlass for professional glass services in the Greater Toronto Area. We look forward to hearing from you.",
    url: siteUrl + "/contact",
    images: [{ url: ogImage }],
    siteName: "OhMyGlass",
    locale: "en_CA",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Contact Us",
    description:
      "Get in touch with OhMyGlass for professional glass services in the Greater Toronto Area. We look forward to hearing from you.",
    images: [ogImage],
  },
  other: { "fb:app_id": "966242223397117" },
};

export default function ContactPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: safeJsonLdScript(contactPageSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: safeJsonLdScript(contactBreadcrumbSchema) }}
      />
      <ContactPageView />
    </>
  );
}
